import React from 'react'

function About() {
  return (
    <div className='h-auto w-[80%] border-2 my-8 p-6 text-black shadow-2xl bg-slate-200 rounded-2xl' id='aboutPage'>
        <h1 className=' font-bold text-2xl border-b-[1px] border-amber-500 mb-4 p-3 text-amber-300'>About</h1>
        <p className='text-slate-700'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores est ea excepturi veniam illum rerum tempore labore dolorum, saepe sit et minima neque quo, magni ullam enim possimus sed consectetur minus qui in error officiis totam voluptate? Optio natus ut sunt repellendus architecto maiores voluptates expedita? Nostrum repudiandae labore ut ipsa nesciunt sequi velit recusandae vel commodi accusantium. Rerum possimus ducimus soluta nulla facilis distinctio nisi laboriosam harum, consequuntur quidem minus molestias qui molestiae, voluptatibus earum maiores unde nostrum vitae optio pariatur porro. Dolores voluptatibus sit, corporis quidem rerum perspiciatis sunt dicta deleniti, repudiandae iste quae repellendus, autem harum? Natus hic distinctio praesentium doloremque illo error molestias excepturi molestiae recusandae, blanditiis deserunt nisi placeat nemo sapiente ea perspiciatis velit, aliquam odio ab obcaecati, odit sunt atque incidunt. Doloremque, corporis iste! Adipisci aut expedita quibusdam doloremque a ipsam asperiores dolorem, quaerat magni eum saepe repudiandae temporibus repellat commodi cupiditate. Sit dolore sunt explicabo unde optio modi, velit, repudiandae pariatur mollitia officia itaque autem hic tenetur! Blanditiis, ut? Quis voluptatibus dicta nobis maxime rem amet facilis libero quos deserunt voluptas consequuntur eveniet, tempore rerum, exercitationem repellendus alias ratione id architecto fugit error vitae eligendi magnam asperiores quam? Ut, consectetur voluptas laudantium numquam vel nulla vitae voluptates magni assumenda eos culpa exercitationem laborum. Delectus velit nihil deserunt maxime repudiandae tempora, temporibus eos earum corporis, dolor asperiores placeat aliquam possimus animi! Harum veritatis neque quisquam nesciunt aliquam, quos ipsa accusamus magnam cumque, enim, reprehenderit maxime consequatur expedita. Repellendus veniam delectus voluptas corporis aliquam repellat!</p>
    </div>
  )
}

export default About